config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(red green blue)

  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w(M F) }

  has_many(
    :cat_rentals,
    class_name: 'CatRentalRequest',
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  def self.colors
    COLORS
  end

  def age
    Date.today.year - self.birth_date.year
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: { in: %w[PENDING APPROVED DENIED] }
  validate :not_double_booked
  after_initialize :default_pending

  belongs_to(
    :cat,
    class_name: 'Cat',
    foreign_key: :cat_id,
    primary_key: :id
  )

  def default_pending
    status ||= "PENDING"
  end

  def overlapping_requests
    overlaps = CatRentalRequest.where("cat_id = ? AND ((start_date BETWEEN ? AND ?)
    OR (end_date BETWEEN ? AND ?) OR (? BETWEEN start_date AND end_date))",
    cat_id, start_date, end_date, start_date, end_date, start_date)

    overlaps
  end

  def not_double_booked
    approved_rentals = overlapping_requests.where(status: 'APPROVED')
    unless approved_rentals.count == 0
      errors[:base] << "time conflict with previous booking!"
    end
  end



  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end


  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<form id="cat_form_id" action=<%= cat.persisted? ? cat_url(@cat) : cats_url %> method="post">
  <% if @cat.persisted? %>
    <input name="_method" type="hidden" value="patch" />
  <% end %>

  <label for="cat_name">Name: </label>
  <input type="text" name="cat[name]" id="cat_name" value=<%= @cat.name %>>
  <br>

  <% ["female", "male"].each do |sex| %>
  <label for="cat_sex_<%= sex %>"><%= sex.capitalize %> </label>
  <input type="radio" name="cat[sex]" id="cat_sex_<%= sex %>"
  value="<%= sex[0].capitalize %>"
  <%= @cat.sex == sex[0].capitalize ? "checked" : nil %> >
  <% end %>

  <br>
  <label for="cat_color">Color: </label>
  <select name="cat[color]" id="cat_color" >
    <option></option>
    <% Cat.colors.each do |color| %>
    <option value=<%= color %>
      <%= @cat.color == color ? "selected" : nil %> >
      <%= color.capitalize %>
    </option>
    <% end %>
  </select>

  <br>

  <label for="cat_birth_date">Birthday: </label>
  <input type="date" name="cat[birth_date]" id="cat_birth_date"
  value=<%= @cat.birth_date %>>

  <br>

  <label for="cat_description">Description: </label>
  <br>
  <textarea name="cat[description]" id="cat_description" rows="5" cols="20"
  placeholder="describe your cat"><%= @cat.description %></textarea>

  <br>
  <input type="submit" value="<%= cat.persisted? ? "Edit" : "Create" %> cat!">
</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat %>

app/views/cats/index.html.erb
<h1>All cats:</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Birth Date</th>
    <th>Description</th>
  </tr>
  <% @cats.each do |cat| %>
    <tr>
      <td><%= link_to cat.name, cat_url(cat) %></td>
      <td><%= cat.color %></td>
      <td><%= cat.age %></td>
      <td><%= cat.sex %></td>
      <td><%= cat.birth_date %></td>
      <td><%= cat.description %></td>
    </tr>
  <% end %>
</table>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat %>

app/views/cats/show.html.erb
<%= @cat.name %> has <%= @cat.color %> fur and is <%= @cat.age %> years old.
<br>
Description: <%= @cat.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninetyninecats</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>